name: Notion Notifier Cron

on:
  schedule:
    # Run at 9 AM JST (00:00 UTC)
    - cron: '0 0 * * *'
    # Run at 1 PM JST (04:00 UTC)
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

jobs:
  run_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Notion Notifier (9 AM JST schedule)
        # Corresponds to 9 AM JST
        if: github.event.schedule == '0 0 * * *'
        run: go run . --daysLater 0

      - name: Run Notion Notifier (1 PM JST schedule)
        # Corresponds to 1 PM JST
        if: github.event.schedule == '0 4 * * *'
        run: go run . --daysLater 3

      - name: Run Notion Notifier (Manual Dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: go run . --daysLater 0
