name: Notion Notifier Cron

on:
  schedule:
    # Run at 9:00 JST (00:00 UTC)
    - cron: '0 0 * * *'
    # Run at 13:00 JST (04:00 UTC)
    - cron: '0 4 * * *'
    # Run at 20:00 JST (11:00 UTC)
    - cron: '0 11 * * *'
  workflow_dispatch:

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

jobs:
  run_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build Go application
        run: go build -o notion-notifier .
      - name: Run Notion Notifier (9 AM JST schedule)
        if: github.event.schedule == '0 0 * * *'
        run: ./notion-notifier --daysLater 3

      - name: Run Notion Notifier (1 PM JST schedule)
        if: github.event.schedule == '0 4 * * *' || github.event_name == 'workflow_dispatch'
        run: ./notion-notifier --daysLater 0
